# Generated by Django 5.2.8 on 2025-12-07 00:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='idea',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='idea',
            index=models.Index(fields=['user', 'created_at'], name='ideas_idea_user_id_3838bc_idx'),
        ),
    ]
