# Generated by Django 5.2.8 on 2025-12-07 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ideas', '0002_alter_idea_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('caption', models.TextField(blank=True)),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('youtube', 'YouTube Shorts')], max_length=20)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('scheduled_date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0, help_text='Sorting weight within the day')),
                ('idea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='ideas.idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_tasks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Task',
                'verbose_name_plural': 'Content Tasks',
                'ordering': ['scheduled_date', 'order', '-created_at'],
                'indexes': [models.Index(fields=['user', 'scheduled_date'], name='planner_con_user_id_93c0c3_idx'), models.Index(fields=['user', 'status'], name='planner_con_user_id_d179c6_idx')],
            },
        ),
    ]
