# Generated by Django 5.2.8 on 2025-12-17 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0002_alter_idea_options_and_more'),
        ('planner', '0002_alter_contenttask_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenttask',
            name='idea',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='task', to='ideas.idea'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contenttask',
            name='scheduled_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='contenttask',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('planned', 'Planned'), ('posted', 'Posted')], default='draft', max_length=20),
        ),
    ]
